# Input file
dataset: 'Ncra_opistho'
input_table_file: 'data/input_tables/Ncraopi.csv'
species_tree: 'data/sptrees/neurospora.spTree.nw'
species_tree_labels: 'data/sptrees/neurospora_internal.spTree.nw'
taxons_file: 'data/meta/Ncra_taxon.csv'
seed: ['UP000001805']
root: 'Atha'