# PARAMS

# Download pipeline
low_confidence: 40
# minimum length of seed protein to keep
min_len: 0

combinations: ["3Di_3Di", "aa_QT", "aa_LG", "3Di_GTR", "3Di_FT"]
#, "3Di_FTPY"]


# target per queries in both foldseek and blast
target_seqs: 1000
max_seqs_brh: 5

# blast evalue
eval_both: 1e-3
coverage: 50
eval_brh: 10

# how many sequence max to do the tree?
max_seqs: 150

# min lddt to mask residues
min_lddt: 50
# Ultrafast bootstrap for iqtree
UF_boot: 1000
# Boostrap for quicktree
distboot: 100

# trimal parameters
# trimal_cons: 30
# trimal_gt: 0.1
# if trimmed aln shorter than this exclude
# min_trim_len: 30

# files and folders
subst_matrix: 'resources/subst_matrixes/mat3di.out'
subst_matrix_tree: 'resources/subst_matrixes/3DI.nexus'

data_dir: 'results/data/'
outdir: 'results/'

n_examples: 50